### ISSUE TITLE
Can't list products in the dashboard product menu creating products vie API

### ISSUE THREAD

**Issue by unclexo** [google/google-my-business-samples#3]
Here is the code below for creating products I use. If I created product this way that would be found to the Posts menu but not in the Products menu. Furthermore,  if I created an event post that would be found in the Dashboard > Posts and then Events tab. Please let me know why this is happening. Thanks in advance.

        $lowerPrice = new Google_Service_MyBusiness_Money;
        $lowerPrice->setCurrencyCode($currency);
        $lowerPrice->setUnits($lowPrice);

        $upperPrice = new Google_Service_MyBusiness_Money;
        $upperPrice->setCurrencyCode($currency);
        $upperPrice->setUnits($highPrice);

        // Prepares local product post
        $localPostProduct = new Google_Service_MyBusiness_LocalPostProduct;
        $localPostProduct->setLowerPrice($lowerPrice);
        $localPostProduct->setUpperPrice($upperPrice);
        $localPostProduct->setProductName($title);

        // Prepares local post
        $localPost = new Google_Service_MyBusiness_LocalPost;
        $localPost->setProduct($localPostProduct);
        $localPost->setSummary($summary);
        $localPost->setMedia($media);

        $localPosts = $this->myBusiness->accounts_locations_localPosts;
        return $localPosts->create($parent, $localPost);

**Comment by ahajalie** [comment]
Products are currently not supported via the API. See the reference documentation for moer info.

https://developers.google.com/my-business/reference/rest

**Comment by grekpg** [comment]
When it will be available in api? And why You just change API without any information. Our API stop working without any info...
